# Generated by Django 4.1.6 on 2023-05-05 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beverages",
            fields=[
                (
                    "item_code1",
                    models.CharField(
                        default="DR00", max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("item_name", models.CharField(max_length=30)),
                (
                    "type1",
                    models.CharField(
                        choices=[
                            ("Alcoholic", "Alcoholic"),
                            ("NonALcoholic", "Non-Alcoholic"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                (
                    "type2",
                    models.CharField(
                        choices=[
                            ("Beer", "Beer"),
                            ("Wine", "Wine"),
                            ("Vodka", "Vodka"),
                            ("Rum", "Rum"),
                            ("Whisky", "Whisky"),
                            ("Tequila", "Tequila"),
                            ("Tea", "Tea"),
                            ("Coffee", "Coffee"),
                            ("FruitJuice", "FruitJuice"),
                            ("SoftDrinks", "SoftDrinks"),
                            ("MilkShake", "MilkShake"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                ("info", models.TextField(max_length=300)),
                ("price", models.IntegerField()),
                ("image_field", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "item_code",
                    models.CharField(
                        default="FD00", max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("item_name", models.CharField(max_length=30)),
                (
                    "type1",
                    models.CharField(
                        choices=[
                            ("Chinese", "Chinese"),
                            ("NorthIndian", "North Indian"),
                            ("SouthIndian", "South Indian"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                (
                    "type2",
                    models.CharField(
                        choices=[("veg", "VEG"), ("nonveg", "NONVEG")],
                        default="na",
                        max_length=20,
                    ),
                ),
                (
                    "type3",
                    models.CharField(
                        choices=[
                            ("BreakFast", "BreakFast"),
                            ("Starters", "Starters"),
                            ("MainCourse", "Main Course"),
                            ("Dessert", "Dessert"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField()),
                ("info", models.TextField(max_length=300)),
                ("image_field", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("is_ordered", models.BooleanField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order_details",
            fields=[
                (
                    "order_id",
                    models.ForeignKey(
                        max_length=12,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="item.order",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("address", models.TextField(max_length=300)),
                ("phone_no", models.CharField(max_length=12)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Goa", "Goa"),
                            ("Maharashtra", "Maharashtra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=20)),
                ("postal_code", models.IntegerField()),
                ("total_price", models.FloatField()),
                ("order_date", models.DateTimeField()),
                ("delivery_date", models.DateTimeField()),
                ("payment_id", models.CharField(max_length=13, unique=True)),
                ("is_purchase", models.BooleanField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="food_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fquantity", models.IntegerField()),
                (
                    "item_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="item.item"
                    ),
                ),
                (
                    "order_idf",
                    models.ForeignKey(
                        max_length=12,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order_idf", "item_code")},
            },
        ),
        migrations.CreateModel(
            name="beverage_cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bqty", models.IntegerField()),
                (
                    "item_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="item.beverages"
                    ),
                ),
                (
                    "order_idb",
                    models.ForeignKey(
                        max_length=12,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="item.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order_idb", "item_code")},
            },
        ),
    ]
